spring.application.name=Service-Discovery


# Allow the application to listen on all network interfaces

server.port = 8250
# Disable replication
eureka.client.service-url.defaultZone=http://localhost:8250/eureka/

eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false